### ISSUE TITLE
R kernel keeps recognizing function params as inputs

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#1032]
```R

```

1. Rewrite the notebook to fix 
2. Add a special comment to override variables -> temporary solution to this issue: https://github.com/QCDIS/NaaVRE/issues/1068
3. Fix the current parser to take into account functions 
4. Student project to add R code analyser -> https://github.com/QCDIS/projects_overview/issues/167

**Comment by gpelouze** [comment]
Workaround through #1068
