### ISSUE TITLE
Start test coverage for frontend code (Cypress)

### ISSUE THREAD

**Issue by r-whites** [QCDIS/NaaVRE#11]

**Comment by skoulouzis** [comment]
Check https://github.com/QCDIS/KMS-generic/blob/master/cypress.config.js 
https://github.com/QCDIS/KMS-generic/blob/master/package.json
https://github.com/QCDIS/KMS-generic/blob/master/cypress/e2e/spec.cy.js 

Set meeting

**Comment by skoulouzis** [comment]
Select elements from Firefox inspector (f12)
