### ISSUE TITLE
Tests fail 'REGISTRY_URL not set' 

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#1109]
We check if the env vars are set so now we get:
REGISTRY_URL not set

**Comment by gpelouze** [comment]
This is fixed by #1087. After this PR, REGISTRY_URL is not needed when deploying to ghcr.io (see https://github.com/QCDIS/NaaVRE-cells#naavre-deployment), so we stop validating it in the actions.
