### ISSUE TITLE
MULTIPLY framework missing models 

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#111]
Having installed multiply_core-0.6.1 and multiply_data_access-0.5.2 on conda : https://github.com/QCDIS/miniconda3-MULTIPLY/commit/a6113bdc00a80a5868425b64929986bd23bd63be 

We run the container:
```
sudo docker run -it 514f430d4a51 /bin/bash
```

Activate the environment:
```
conda activate venv
```

Run the python MULTIPLY:
```
python -c "from multiply_data_access import DataAccessComponent"
```
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/venv/lib/python3.6/site-packages/multiply_data_access/__init__.py", line 1, in <module>
    from .data_access import DataSetMetaInfo, FileSystem, MetaInfoProvider
  File "/opt/conda/envs/venv/lib/python3.6/site-packages/multiply_data_access/data_access.py", line 15, in <module>
    from multiply_core.observations import differs_by_name, get_relative_path
  File "/opt/conda/envs/venv/lib/python3.6/site-packages/multiply_core/observations/__init__.py", line 1, in <module>
    from .observations import ProductObservations, ObservationData, ProductObservationsCreator, ObservationsFactory, \
  File "/opt/conda/envs/venv/lib/python3.6/site-packages/multiply_core/observations/observations.py", line 18, in <module>
    from ..models.forward_models import get_forward_models
ModuleNotFoundError: No module named 'multiply_core.models'
```

**Comment by skoulouzis** [comment]
More detailed steps to reproduce:
```
git clone https://github.com/QCDIS/miniconda3-MULTIPLY.git
cd miniconda3-MULTIPLY
sudo docker build .
```
We get the docker build image ID and run the image:
```
sudo docker run -it IMAGE_ID /bin/bash
```
Activate the environment:
```
conda activate venv
```
Run the python MULTIPLY:
```
python -c "from multiply_data_access import DataAccessComponent"
```

**Comment by JorisTimmermans** [comment]
The error was caused as the 'multiply_core.models directory' was not included within the setup.py (for was used to create the wheel that this image uses). I have solved this by updating 'https://github.com/JorisTimmermans/multiply_core', and have created an updated wheel file (that does include the models directory) which can be found in "https://github.com/JorisTimmermans/multiply-core/releases/download/v0.1.1/multiply_core-0.6.1.dev0-py3-none-any.whl.
