### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#1136]
We start to have a lot of major versions failing to update in nodeJS packages. 

Also, Jupiter Lab is now at  4.10 while we are at 3.5. 
To keep up with all the updates we need to refactor the project entirely. 

Build extensions using https://github.com/jupyterlab/extension-template

**Comment by gpelouze** [comment]
Duplicate of https://github.com/QCDIS/projects_overview/issues/226
