### ISSUE TITLE
Cell build fails

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#1236]
In the NaaVRE-cells-test-2  we get errors on the docker build:
https://github.com/QCDIS/NaaVRE-cells-test-2/actions/runs/8187237166/job/22387281301
```
   1 | >>> FROM  AS build
   2 |     COPY --chown=$MAMBA_USER:$MAMBA_USER environment.yaml .
   3 |     RUN micromamba install -y -n venv -f environment.yaml 
```

**Comment by gpelouze** [comment]
@skoulouzis does it work when running NaaVRE with `BASE_IMAGE_TAGS_URL=https://github.com/QCDIS/NaaVRE-flavors/releases/download/v0.6/base_image_tags.json`?

When it is not set, we fall back to https://raw.githubusercontent.com/QCDIS/NaaVRE-conf/main/base_image_tags.json in [`component_containerizer/handlers.py#L228`](https://github.com/QCDIS/NaaVRE/blob/b83bc907a9b281d51c789a2e1a3a659e89fad9d6/jupyterlab_vre/component_containerizer/handlers.py#L228), which doesn’t have the `build` and `runtime` base image. As a result, [`dockerfile_template_conda.jinja2`](https://github.com/QCDIS/NaaVRE/blob/b83bc907a9b281d51c789a2e1a3a659e89fad9d6/jupyterlab_vre/templates/dockerfile_template_conda.jinja2#L1) is rendered with an empty base image.

If adding `BASE_IMAGE_TAGS_URL` solves the problem, we should change the default value in `component_containerizer/handlers.py`.

**Comment by gpelouze** [comment]
Another option is to update https://raw.githubusercontent.com/QCDIS/NaaVRE-conf/main/base_image_tags.json to match the contents of https://github.com/QCDIS/NaaVRE-flavors/releases/download/v0.6/base_image_tags.json.

Or even better, using the `latest` tags.

**Comment by gpelouze** [comment]
We should use `https://github.com/QCDIS/NaaVRE-flavors/releases/latest/download/base_image_tags.json` as the default value for `BUSE_IMAGE_TAGS_URL`

**Comment by gpelouze** [comment]
This is done in #1263
