### ISSUE TITLE
Fix BASE_IMAGE_TAGS_URL in CI pipeline

### ISSUE THREAD

**Issue by gpelouze** [QCDIS/NaaVRE#1261]
- Create a new empty NaaVRE-cells repository and use it to run tests from NaaVRE → tests should fail because the generated docker files have empty base image names
- Set `BASE_IMAGE_TAGS URL=https://github.com/QCDIS/NaaVRE-flavors/releases/latest/download/base_image_tags.json` on NaaVRE and re-run the tests → should fix the issue
- After it is fixed, we can fix #1236 by setting the default value of `BASE_IMAGE_TAGS URL`

**Comment by skoulouzis** [comment]
Created https://github.com/QCDIS/NaaVRE-cells-test-3

**Comment by skoulouzis** [comment]
Set CELL_GITHUB to https://github.com/QCDIS/NaaVRE-cells-test-3.git
