### ISSUE TITLE
List cannot be used as `param_`

### ISSUE THREAD

**Issue by gpelouze** [QCDIS/NaaVRE#1321]
It is not possible to use a list as `param_`. Here is an overview of the current situation.

* It is possible to containerize a cell setting the `param_` data type as `List`. The list type gets correctly rendered within the cell: `arg_parser.add_argument('--param_test', action='store', type=list, required=True, dest='param_test')`

* When providing a list (eg `['Alice', 'Bob']`) for the `param_`, the value makes it to the submission, but is dropped by Argo:
  * NaaVRE logs excerpt:
    ```
    INFO:jupyterlab_vre.experiment_manager.handlers Workflow submission request:
      "workflow_payload.workflow.spec.arguments.parameters": [{
        "name": "param_test",
        "value": ["Alice", "Bob"]
      }]
    ```
  * Workflow:

    ![Image](https://github.com/QCDIS/NaaVRE/assets/9514702/136da8bc-31d6-4a45-b206-1de9f09ed4ae)

    ```
    Namespace(id='1b9d935', param_test=[])
    []
    ```

* When providing a string (`Something`)
  * NaaVRE logs excerpt:
    ```
    INFO:jupyterlab_vre.experiment_manager.handlers Workflow submission request:
      "workflow_payload.workflow.spec.arguments.parameters": [{
        "name": "param_test",
        "value": "Something"
      }]
    ```
  * Workflow:

    ![Image](https://github.com/QCDIS/NaaVRE/assets/9514702/a19de391-7d08-4f42-b380-b9e7768cbb24)

    ```
    Namespace(id='1b9d935', param_test=['S', 'o', 'm', 'e', 't', 'h', 'i', 'n', 'g'])
    ['S', 'o', 'm', 'e', 't', 'h', 'i', 'n', 'g']
    ```

* Providing a serialized list doesn’t work either (`"['Alice', 'Bob']"`):
  * Workflow:

    ```
    Namespace(id='1b9d935', param_test=['[', 'A', 'l', 'i', 'c', 'e', ',', ' ', 'B', 'o', 'b', ']'])
    ['[', 'A', 'l', 'i', 'c', 'e', ',', ' ', 'B', 'o', 'b', ']']
    ```

---

We want to make it possible for users to provide a list as param.

Two options:
- pass a list as workflow parameter (check argo support)
- serialized the list before rendering the workflow template, and deserialize when running the cell.

**Comment by skoulouzis** [comment]
Try to use JSON serializer/deserializer
