### ISSUE TITLE
Research for R linter

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#1381]
Look for an equivalent for pyflakes to identify inputs. This is done by looking for variables that are used but not defined in a call 
Possible solutions: 

- https://lintr.r-lib.org/ 
- Keep track of vars in a list
-

**Comment by jordiboon** [comment]
lintr doesn't seem to have any functions to detect variables that are used but have not been defined. Only _object_usage_linter()_ does something like this but only within functions:

```
x <- function(y) {
    print(z)
}

/home/wsl/testcode/undef.r:2:11: warning: [object_usage_linter] no visible binding for global variable 'z'
    print(z)
```

Current method I use is to first extract all defined variables within a script, then extracting all variables that are not in the list of defined variables while also keeping track of scoped variables and built-in constants
