### ISSUE TITLE
Automate type inference

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#164]
Automate type inference on the containerizer. 
End-users are not familiar with variable types

**Comment by gpelouze** [comment]
We want to pre-fill the variable types in the cell-containerization form. To do this, we will look for a existing tool to infer type from the code. If the users are not satisfied with the infered type, they can override it in the form or with type annotations.

**Comment by gpelouze** [comment]
Deployed on https://lifewatch.lab.uvalight.net/n-a-a-vre/ and tested on https://github.com/QCDIS/Life-Watch-Summer-School-2023-materials/blob/laserfarm/Laserfarm/Laserfarm_demo.ipynb
