### ISSUE TITLE
When creating a new cell and deleting a title the Component containerizer shows the least "valid" cell 

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#30]
Steps to recreate:

1. create a new cell 
2. add comment/title on the top of the cell-> Component containerizer shows the title in the component
3. delete the comment/title on the top of the cell 
4. Click on another cell with  comment/title 
5. Click back to cell -> Component containerizer shows the title of the previous component

**Comment by r-whites** [comment]
Is the notebook saved in between the change in selection of the cells?

**Comment by skoulouzis** [comment]
Yes, it is. 
Repeated as in screencast. 

https://user-images.githubusercontent.com/9680609/148525712-059586ca-73f6-4164-80d8-c8c95da5bbf9.mp4

**Comment by skoulouzis** [comment]
delete due to inactivity
