### ISSUE TITLE
Get more metadata from API eg. author num of cells 

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#343]
For better presentation add some metadata on the results box .

**Comment by skoulouzis** [comment]
source of the notebook. 
Author but not necessary.
Nice if we can get the last update date.

**Comment by nali001** [comment]
The backend is done. 
Added some metadata 
{
    'source': notebook source, 
    'language': kernel type, 
    'num_cells': number of cells
}

**Comment by skoulouzis** [comment]
Got the results from the API
