### ISSUE TITLE
Deploy container with rclone in test cluster

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#378]
From https://github.com/QCDIS/NaaVRE/tree/datamesh build and deploy the container with rclone

**Comment by JustinMingo** [comment]
No luck. When I launch a terminal it can't find rclone.

Utrecht university has it: https://utrechtuniversity.github.io/research-engineering/manuals/install-rclone/

I get the following errors when I try that (something with privileges?):

jovyan@jupyter-justinmingo:~$ rclone config
bash: rclone: command not found

jovyan@jupyter-justinmingo:~$ curl https://rclone.org/install.sh | sudo bash

sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4669  100  4669    0     0  27427      0 --:--:-- --:--:-- --:--:-- 27627
curl: (23) Failure writing output to destination

jovyan@jupyter-justinmingo:~$ rclone version
bash: rclone: command not found

**Comment by skoulouzis** [comment]
Will try to install with apt and rebuild the image

**Comment by skoulouzis** [comment]
We can also use : conda install -c conda-forge rclone

**Comment by JustinMingo** [comment]
Rclone works, S3 I think also:

Current remotes:

Name                 Type
====                 ====
test                 s3

**Comment by JustinMingo** [comment]
- [ ] Check if we can move files from and to S3.

**Comment by skoulouzis** [comment]
rclone from apt installs 1.50.2 
rclone from conda installs 1.60.1
