### ISSUE TITLE
Component containerizer builds containers without python

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#39]
**Describe the bug**
We build the cell from Component containerizer, push it to docker but the workflow execution in argo fails.
The output from argo:

/bin/bash: python: command not found
Exit code
127

**Comment by skoulouzis** [comment]
Seems that venv is not activated or python is not pointing at the correct location

**Comment by r-whites** [comment]
The virtual environment is indeed not being activated. Reason being the activation command has been removed by the latest commit while testing with the base python image (without conda)
