### ISSUE TITLE
Rclone-enabled Lifewatch FailedPostStartHook

### ISSUE THREAD

**Issue by JustinMingo** [QCDIS/NaaVRE#421]
CalledProcessError: Command '['git', 'fetch']' returned non-zero exit status 128. , message: "$ git fetch\n\nfatal: not a git repository (or any parent up to mount point /home)\n\nStopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by skoulouzis** [comment]
Had to delete the example_wroklfows folder manually from the PVC.
Seems we had a git conflict
