### ISSUE TITLE
retailing cell fails to print output 

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#43]
**Describe the bug**
retailing cell  after the processing trys to print a pathlib 
```python
import json
outs = {}
outs['remote_path_retiled'] = remote_path_retiled
print(json.dumps(outs))
```
We get this error:
```python
{'remote_path_retiled': PosixPath('/webdav/retiled')}
Traceback (most recent call last):
  File "retiling-1.py", line 58, in <module>
    print(json.dumps(outs))
  File "/venv/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/venv/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/venv/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/venv/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PosixPath is not JSON serializable
```

**Comment by r-whites** [comment]
`{'remote_path_retiled': PosixPath('/webdav/retiled')}` shows that the object assigned is not the innermost string value for the path, but instead the path object itself. In this case, introducing a forced conversion to string of certain or the implementation of a custom serialiser might be a solution.

**Comment by skoulouzis** [comment]
Instruct user to use types available in the type containerized panel

**Comment by r-whites** [comment]
It might be possible to tackle it in this manner: https://github.com/kubeflow-kale/kale/tree/master/backend/kale/marshal
