### ISSUE TITLE
Error building the code

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#582]
When running:
```
make install-backend && make build-frontend && make install-ui && make link-ui
```

We get an error:
```python
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from pathlib import Path
ImportError: No module named pathlib
make: *** [build-backend] Error 1
```

**Comment by DiederikBlanson** [comment]
Hi @skoulouzis, this was an issue on my end (conda was not correctly installed locally). So we can close this ticket :)

**Comment by skoulouzis** [comment]
@DiederikBlanson  Can you add the steps you followed to resolve this so we have this for future reference

**Comment by DiederikBlanson** [comment]
@skoulouzis Yes I will do:

I removed Anaconda entirely from my machine (MacOS), and did a full reinstall as follows:
```
brew install anaconda
export PATH="/usr/local/anaconda3/bin:$PATH"
```

Next, setting up the Anaconda environment:
```
conda create -n jupyterlab  python=3.9 
conda activate jupyterlab
```

While in our session the command `python --version` gave version 2.7 (and we fixed it temporarily with the file `~/.base_profile` redirecting to python3), it now gives 3.9 (as expected). As such, the following command was succesfully executed `make install-backend && make build-frontend && make install-ui && make link-ui `
