### ISSUE TITLE
Retrieve base images based on the type of kernel

### ISSUE THREAD

**Issue by DiederikBlanson** [QCDIS/NaaVRE#595]
At the moment, the options for the base-images for the Containerizer Component are fixed on the frontend.

I would propose to make an API call to the backend which retrieves the possible base images based on the type of kernel, or detection of the programming language.

As such, we will be able to suggest base-images for other programming languages such as R.

**Comment by DiederikBlanson** [comment]
@skoulouzis Is this desirable?

**Comment by skoulouzis** [comment]
That is a nice feature to have but it's not so urgent.

**Comment by skoulouzis** [comment]
Timeout
