### ISSUE TITLE
Create simple template for the SDIA UI

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#61]
We want to have SDIA provision and deploy VREs for users/communities. 

Build a prototype web application based on Jdgango.
Functionality is going to be the same as currently in extension.

**Comment by r-whites** [comment]
<img width="757" alt="Screenshot 2022-02-08 at 15 16 26" src="https://user-images.githubusercontent.com/1097168/153004894-c207773e-9923-4370-abce-c1b461b485d8.png">
