### ISSUE TITLE
Install R kernel

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#626]
Install R kernel in Jupyterlab. 
Find how to do that (write down steps)

**Comment by DiederikBlanson** [comment]
1. Before we can install the R kernel, we need to have an R version installed.

2. If that is the case, we can install the IRKernel with conda as follows:

`conda install -c r r-irkernel`.

3. To make it available in Jupyter (and in the Launcher) run the command `R -e "IRKernel::installspec()`

This should work (tested it locally).
