### ISSUE TITLE
Test containerization. Test push and fix credentials

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#629]
Create the VARS file to push the container in Github.

**Comment by DiederikBlanson** [comment]
@skoulouzis when I execute the command: `source export_VARS && jupyter lab build && cp -r ~/workspace/NaaVRE/docker/repo_utils/ /tmp/ && ~/workspace/NaaVRE/docker/init_script.sh && jupyter lab --debug --watch --NotebookApp.token='' --NotebookApp.ip='0.0.0.0' --NotebookApp.allow_origin='*'`

I get the following error:
`
[LabBuildApp] WARNING | Config option `kernel_spec_manager_class` not recognized by `LabBuildApp`.
[LabBuildApp] JupyterLab 3.6.1
[LabBuildApp] Building in /Users/diederikblansonhenkemans/miniforge3/envs/jupyterlab/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (development)
cp: /tmp/repo_utils/conf_vl_repos.py: No such file or directory
[2023-05-06 15:26:39,158] INFO -- Repo example_notebooks doesn't exist. Cloning...
$ git clone --depth 1 --branch main -- https://github.com/QCDIS/lifewatch-notebooks example_notebooks

Cloning into 'example_notebooks'...

[2023-05-06 15:26:47,378] INFO -- Repo example_notebooks initialized
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
unzip:  cannot find or open /tmp/multiply.zip, /tmp/multiply.zip.zip or /tmp/multiply.zip.ZIP.
python: can't open file '/tmp/repo_utils/conf_vl_repos.py': [Errno 2] No such file or directory
`

It seems that the file ` /tmp/repo_utils/conf_vl_repos.py` cannot be found. Do you know how to fix this?

**Comment by DiederikBlanson** [comment]
I am getting the error `Error getting repository: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest"}` in the CellsHandler post-request

**Comment by DiederikBlanson** [comment]
Update: credentials work now

**Comment by DiederikBlanson** [comment]
@skoulouzis I am able to push the containers to GitHub. There is still one issue with running the workflow in Argo, but we have a separate ticket for that. I propose we close this one.

**Comment by DiederikBlanson** [comment]
- Conda install
- Docker install

**Comment by skoulouzis** [comment]
We deploy the prototype version
