### ISSUE TITLE
Publish dependencies code on git 

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#66]
We need to get the dependencies  source so we can build the wheel file

**Comment by JorisTimmermans** [comment]
I have made available the repositories of the modified MULTIPLY components. They can now be found at my own git account https://github.com/JorisTimmermans. I also updated the install_download_multiply_modules.sh file to use these repositories instead of the local zip archive

**Comment by skoulouzis** [comment]
We may use actions to build all the wheel packages: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

**Comment by skoulouzis** [comment]
We'll build a base conda image with the dependencies installed. This will be used for both the Jupiter image and the Argo image 

https://github.com/QCDIS/miniconda3-MULTIPLY

**Comment by skoulouzis** [comment]
We now MULTIPLY install from pip and git
