### ISSUE TITLE
F is not recognized as FALSE   as a boolean

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#682]
F is not recognized as FALSE:
If we have this line:

```
write.table(df.merged,paste('output/dfmerged.csv',sep=''),row.names=F,sep = ";",dec = ".",quote=FALSE)
```

The containerizer sees it as input:

![Screenshot from 2023-06-13 13-48-16](https://github.com/QCDIS/NaaVRE/assets/9680609/f78ffcbf-5491-4248-bcf8-68e5dfa2165e)

Instead, if we declare it as FALSE:

```
write.table(df.merged,paste('output/dfmerged.csv',sep=''),row.names=FALSE,sep = ";",dec = ".",quote=FALSE)
```

The containerizer sees it as a boolean:
![Screenshot from 2023-06-13 13-49-47](https://github.com/QCDIS/NaaVRE/assets/9680609/a16d3808-5477-4e48-8cf5-79890740283d)

**Comment by DiederikBlanson** [comment]
@skoulouzis this one has been solved as the variables T and F are removed from input/output variables
