### ISSUE TITLE
library names are treated as inputs

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#683]
If we use a library:
```R
install.packages("dplyr")
library(dplyr) 
```

Then we get:
![Screenshot from 2023-06-13 13-51-18](https://github.com/QCDIS/NaaVRE/assets/9680609/31b02828-352a-43d6-ad17-6b4e631bf771)

As a workaround, we declare it as a variable:

```R
install.packages("dplyr")
dplyr = ''
library(dplyr) 
```
![Screenshot from 2023-06-13 13-52-05](https://github.com/QCDIS/NaaVRE/assets/9680609/df29ccef-033d-405e-a0aa-bbc13ef98eb1)

**Comment by DiederikBlanson** [comment]
@skoulouzis we could also check whether the variable name (dplyr here) is in the list of packages (`def __extract_imports`), if that is the case, we skip it for the inputs?

**Comment by DiederikBlanson** [comment]
If we add the dependencies in the containerizer, the "dplyr" module is automatically removed

PR: https://github.com/QCDIS/NaaVRE/pull/687

<img width="1150" alt="Screenshot 2023-06-16 at 12 09 19" src="https://github.com/QCDIS/NaaVRE/assets/31020247/cc96d4c9-a5fb-44b6-99c3-ad008c66b5cd">
