### ISSUE TITLE
containerizer is not recognizing '<-' 

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#684]
Containerizer is not recognizing '<-'  we are now using '='

**Comment by DiederikBlanson** [comment]
@skoulouzis In which cases doesnt it work? Below a working example

<img width="772" alt="Screenshot 2023-06-16 at 10 56 45" src="https://github.com/QCDIS/NaaVRE/assets/31020247/143991af-9608-4d01-a310-68268d6be8d6">
