### ISSUE TITLE
On testing we get API rate limit exceeded for  xx.xx.xx.xx

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#894]
```
FAILED jupyterlab_vre/tests/test_handlers.py::HandlersAPITest::test_cells_handler - Exception: Error getting jobs for workflow run: {"message":"API rate limit exceeded for 20.75.95.96. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

**Comment by skoulouzis** [comment]
From: https://stackoverflow.com/questions/64793785/do-the-github-api-rate-limits-apply-to-github-actions 

curl -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/rate_limit

So you can add that call (which does not count against your REST API rate limit) before and after your other REST API calls, and you will see how said rate is impacted.

**Comment by gpelouze** [comment]
Maybe the following works: 

https://github.com/QCDIS/kb-indexer/blob/a1db4aeab1fde84d2a9f2eb959d6e4af497cdd34/indexers/notebook/searching.py#L109C14-L109C14

```python
def wait_for_api_resource(g):
    while g.get_rate_limit().search.remaining <= 0:
        print('API rate exceeded, waiting')
        time.sleep(10)

g = GitHub(api_token)
wait_for_api_resource(g)
```

But we need to replace `search` with the appropriate token

**Comment by gpelouze** [comment]
Double check on a PR that still has the same error. Do a merge & verify that the check is performed. Do another push, release, and check again.
