### ISSUE TITLE
Dependency resolution fails with `import module.submodule as alias`

### ISSUE THREAD

**Issue by gpelouze** [QCDIS/NaaVRE#939]
`import module.submodule as alias` identifies `module.submodule` as dependency.

This results in `failed to solve: process "/bin/sh -c conda env update -n venv -f ***-environment.yaml" did not complete successfully: exit code: 1` when building the cell. 

The correct behaviour is to identify `module` as dependency.

**Comment by skoulouzis** [comment]
We get an error in class IOLoop(Configurable) line 525:
```python
        if future_cell[0].cancelled() or not future_cell[0].done():
            raise TimeoutError("Operation timed out after %s seconds" % timeout)
```
The error comes when we test laserfarm.json
